// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'beam_guard_test.dart' as beam_guard_test;
import 'beam_location_test.dart' as beam_location_test;
import 'beamer_route_information_parser_test.dart' as beamer_route_information_parser_test;
import 'beamer_router_delegate_test.dart' as beamer_router_delegate_test;
import 'beamer_test.dart' as beamer_test;
import 'utils_test.dart' as utils_test;

void main() {
  beam_location_test.main();
  beamer_router_delegate_test.main();
  utils_test.main();
  beamer_test.main();
  beamer_route_information_parser_test.main();
  beam_guard_test.main();
}
