name: CI

on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'package/**'
  pull_request:
    branches:
      - master
    paths:
      - 'package/**'

jobs:
  test:
    defaults:
      run:
        working-directory: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
